---
name: test
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  setup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  tfmigrate-plan:
    timeout-minutes: 30
    name: "tfmigrate-plan (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    needs: setup
    # if services is empty, the build job is skipped
    if: "false"
    steps:
      - run: "true"

  terraform-plan:
    timeout-minutes: 30
    name: "terraform-plan (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    needs: setup
    # if services is empty, the build job is skipped
    if: "false"
    steps:
      - run: "true"

  # This job is used for branch protection rule
  # Add this job to `Status checks that are required`
  status-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [terraform-plan, tfmigrate-plan, setup]
    if: failure()
    steps:
      - run: exit 1
